/* ============================================================
   技能图标 —— 每个技能一枚专属图标
   ------------------------------------------------------------
   不给 100+ 个技能逐一拍板画什么，而是：定一份够大、够分得开的
   图标池（下面这张表，名字全部经 @phosphor-icons/react 的导出清单
   核对过），再按技能 id 做一次确定性分配（见 iconOf）：同一个
   技能每次拿到的图标永远一样，不同技能尽量不撞车。
   ============================================================ */

import type { Icon } from '@phosphor-icons/react'
import {
  Sword,
  Axe,
  Hammer,
  Screwdriver,
  Wrench,
  GearSix,
  Toolbox,
  Nut,
  Crosshair,
  CrosshairSimple,
  Target,
  Binoculars,
  MagnifyingGlass,
  Shield,
  ShieldChevron,
  ShieldStar,
  ShieldSlash,
  HandFist,
  HandWaving,
  HandsPraying,
  PersonSimpleRun,
  PersonArmsSpread,
  Person,
  Users,
  UserFocus,
  Lightning,
  Fire,
  Flame,
  Campfire,
  Drop,
  DropSimple,
  DropHalf,
  Snowflake,
  Tornado,
  Hurricane,
  CloudRain,
  CloudLightning,
  CloudFog,
  Wind,
  Sun,
  Moon,
  MoonStars,
  Star,
  StarFour,
  StarHalf,
  ShootingStar,
  Sparkle,
  Planet,
  Atom,
  Infinity,
  Aperture,
  Hexagon,
  Diamond,
  Triangle,
  Pentagon,
  Circle,
  CircleHalf,
  CirclesThree,
  CirclesFour,
  Skull,
  Bone,
  Brain,
  Ghost,
  Robot,
  Bug,
  Butterfly,
  PawPrint,
  Feather,
  Bird,
  Cat,
  Dog,
  Horse,
  Rabbit,
  Fish,
  Eye,
  EyeSlash,
  Ear,
  Heart,
  Heartbeat,
  HeartStraight,
  HeartHalf,
  Guitar,
  MusicNotes,
  Metronome,
  PianoKeys,
  Microphone,
  SpeakerHigh,
  Headphones,
  Radio,
  VinylRecord,
  Disc,
  Broadcast,
  Waveform,
  WaveSine,
  WaveSquare,
  Waves,
  Rocket,
  RocketLaunch,
  Airplane,
  Anchor,
  Compass,
  MapPin,
  MapTrifold,
  Path,
  Signpost,
  Bookmark,
  Books,
  Book,
  BookOpen,
  Scroll,
  FileText,
  Package,
  Briefcase,
  Flask,
  TestTube,
  Funnel,
  PlugsConnected,
  Tree,
  Leaf,
  Flower,
  FlowerLotus,
  Plant,
  Cactus,
  Mountains,
  CastleTurret,
  Church,
  Buildings,
  Factory,
  House,
  Tent,
  Bridge,
  RoadHorizon,
  TrafficSign,
  Strategy,
  PuzzlePiece,
  Cards,
  PokerChip,
  Crown,
  CrownSimple,
  Medal,
  MedalMilitary,
  Trophy,
  Certificate,
  Seal,
  Stamp,
  Signature,
  PenNib,
  Scissors,
  Lightbulb,
  LightbulbFilament,
  Flashlight,
  Lamp,
  Siren,
  Megaphone,
  MegaphoneSimple,
  Bell,
  BellRinging,
  CheckFat,
  WarningDiamond,
  Lock,
  LockOpen,
  LockKey,
  Key,
  Fingerprint,
  Clock,
  ClockCounterClockwise,
  Timer,
  Hourglass,
  HourglassHigh,
  CalendarDots,
  ArrowsClockwise,
  ArrowsOut,
  ArrowsIn,
  ArrowsLeftRight,
  ArrowsDownUp,
  ArrowsMerge,
  ArrowsSplit,
  ArrowUp,
  ArrowDown,
  ArrowBendUpRight,
  ArrowBendDownRight,
  Repeat,
  Shuffle,
  FastForward,
  Rewind,
  Play,
  Pause,
  Record,
  SlidersHorizontal,
} from '@phosphor-icons/react'

/** 图标池：技能 id 依次从这里取，取完一轮才回头复用 */
export const SKILL_ICON_POOL: Record<string, Icon> = {
  Sword,
  Axe,
  Hammer,
  Screwdriver,
  Wrench,
  GearSix,
  Toolbox,
  Nut,
  Crosshair,
  CrosshairSimple,
  Target,
  Binoculars,
  MagnifyingGlass,
  Shield,
  ShieldChevron,
  ShieldStar,
  ShieldSlash,
  HandFist,
  HandWaving,
  HandsPraying,
  PersonSimpleRun,
  PersonArmsSpread,
  Person,
  Users,
  UserFocus,
  Lightning,
  Fire,
  Flame,
  Campfire,
  Drop,
  DropSimple,
  DropHalf,
  Snowflake,
  Tornado,
  Hurricane,
  CloudRain,
  CloudLightning,
  CloudFog,
  Wind,
  Sun,
  Moon,
  MoonStars,
  Star,
  StarFour,
  StarHalf,
  ShootingStar,
  Sparkle,
  Planet,
  Atom,
  Infinity,
  Aperture,
  Hexagon,
  Diamond,
  Triangle,
  Pentagon,
  Circle,
  CircleHalf,
  CirclesThree,
  CirclesFour,
  Skull,
  Bone,
  Brain,
  Ghost,
  Robot,
  Bug,
  Butterfly,
  PawPrint,
  Feather,
  Bird,
  Cat,
  Dog,
  Horse,
  Rabbit,
  Fish,
  Eye,
  EyeSlash,
  Ear,
  Heart,
  Heartbeat,
  HeartStraight,
  HeartHalf,
  Guitar,
  MusicNotes,
  Metronome,
  PianoKeys,
  Microphone,
  SpeakerHigh,
  Headphones,
  Radio,
  VinylRecord,
  Disc,
  Broadcast,
  Waveform,
  WaveSine,
  WaveSquare,
  Waves,
  Rocket,
  RocketLaunch,
  Airplane,
  Anchor,
  Compass,
  MapPin,
  MapTrifold,
  Path,
  Signpost,
  Bookmark,
  Books,
  Book,
  BookOpen,
  Scroll,
  FileText,
  Package,
  Briefcase,
  Flask,
  TestTube,
  Funnel,
  PlugsConnected,
  Tree,
  Leaf,
  Flower,
  FlowerLotus,
  Plant,
  Cactus,
  Mountains,
  CastleTurret,
  Church,
  Buildings,
  Factory,
  House,
  Tent,
  Bridge,
  RoadHorizon,
  TrafficSign,
  Strategy,
  PuzzlePiece,
  Cards,
  PokerChip,
  Crown,
  CrownSimple,
  Medal,
  MedalMilitary,
  Trophy,
  Certificate,
  Seal,
  Stamp,
  Signature,
  PenNib,
  Scissors,
  Lightbulb,
  LightbulbFilament,
  Flashlight,
  Lamp,
  Siren,
  Megaphone,
  MegaphoneSimple,
  Bell,
  BellRinging,
  CheckFat,
  WarningDiamond,
  Lock,
  LockOpen,
  LockKey,
  Key,
  Fingerprint,
  Clock,
  ClockCounterClockwise,
  Timer,
  Hourglass,
  HourglassHigh,
  CalendarDots,
  ArrowsClockwise,
  ArrowsOut,
  ArrowsIn,
  ArrowsLeftRight,
  ArrowsDownUp,
  ArrowsMerge,
  ArrowsSplit,
  ArrowUp,
  ArrowDown,
  ArrowBendUpRight,
  ArrowBendDownRight,
  Repeat,
  Shuffle,
  FastForward,
  Rewind,
  Play,
  Pause,
  Record,
  SlidersHorizontal,
}

export const SKILL_ICON_NAMES: string[] = Object.keys(SKILL_ICON_POOL)

/* ---------- 确定性分配 ---------- */

/** 技能 id → 图标名（FNV-1a，取模落进池子） */
const SEEDED = new Map<string, string>()

function hash(s: string): number {
  let h = 0x811c9dc5
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i)
    h = Math.imul(h, 0x01000193) >>> 0
  }
  return h >>> 0
}

/**
 * 给一个技能挑一枚专属图标：同一 id 恒定同一枚；
 * 若与已分配过的技能撞车，就顺着池子往下linear probe 一枚没被占的。
 * 池子（189 枚）比全库技能数宽裕，正常用不满一轮，撞车只是兜底。
 */
export function iconNameOf(skillId: string): string {
  const hit = SEEDED.get(skillId)
  if (hit) return hit
  const taken = new Set(SEEDED.values())
  const n = SKILL_ICON_NAMES.length
  let i = hash(skillId) % n
  for (let k = 0; k < n && taken.has(SKILL_ICON_NAMES[i]); k++) i = (i + 1) % n
  const name = SKILL_ICON_NAMES[i]
  SEEDED.set(skillId, name)
  return name
}

/** 技能 id → 图标组件 */
export function iconOf(skillId: string): Icon {
  return SKILL_ICON_POOL[iconNameOf(skillId)]
}
